### ISSUE TITLE
onViewableItemsChanged no triggered after the first section

### ISSUE THREAD

**Issue by guicara** [marcocesarato/react-native-big-list#120]
Hello,

I use the [Section List](https://marcocesarato.github.io/react-native-big-list-docs/basics/sections-list) to display an alphabetical list of contacts. Each section correspond to a letter of the alphabet. Next to the list, there is a vertical component that display an alphabetical index (A to Z).

I would like to highlight the active section (letter) on this component. For that, the `onViewableItemsChanged` callback seems to be the answer.

However, it is not working as expected.

The event is only fired for the first section (in my contact app example, for the letter "A"). When the user scroll to the next section, the event is not triggered at all.

Thanks

**Comment by labtorie** [comment]
Facing the same issue

**Comment by guicara** [comment]
@labtorie unfortunately no. And it's a big limitation.

**Comment by labtorie** [comment]
> @labtorie unfortunately no. And it's a big limitation.

Thanks for a quick response.

By any chance, do you know any other way to implement the list we both need, as perfomant as this one is, and without that kind of problems?

**Comment by guicara** [comment]
The only solution I see will be to debug this library and create a PR.

**Comment by labtorie** [comment]
Hey. I guess I've found the problem. All you need to do is to patch ```BigList.js```. The problem is in this line [https://github.com/marcocesarato/react-native-big-list/blob/a50c24922e0f83226ba30a3626ab32bba74733d7/lib/BigList.jsx#L584](url)

You need to replace ```section[sections]``` with ```section[s]```

**Comment by guicara** [comment]
Hello,

I've installed the last release (version 1.5.3).
I can confirm that the bug is now fixed. The event `onViewableItemsChanged` is now triggered for each section of the list.

Again, thank you @labtorie @marcocesarato.

Have a nice day
