### ISSUE TITLE
 `ScrollViewComponent` of type `object` supplied to `BigList`

### ISSUE THREAD

**Issue by AnisLarguet123** [marcocesarato/react-native-big-list#141]
i have copied the same example as you mentioned but i got this error ? 
`  <BigList
                headerHeight={100} // Default 0, need to specify the header height
                footerHeight={100} // Default 0, need to specify the footer  height
    
        //  renderEmpty={renderItemEmpty}
          ListEmptyComponent= {renderItemEmpty}
          placeholder
          onRefresh={() => onRefresh()}
          refreshing={state.isFetching}          
          contentContainerStyle={{
           display:"flex",
           alignItems:"center",
           justifyContent:"center"
            }}
          data={data}
          placeholderComponent={()=>(<View />)}
          ScrollViewComponent ={ScrollView}
         // renderItem={({item,index})=>renderItem({item,index}) }
          renderItem={renderItem}
          itemHeight={height+20} 
          keyExtractor={(item, index) => `keyExtractor_${index.toString()}`}
          ListFooterComponent={renderLoader}
          onEndReached={loadMore}
          onEndReachedThreshold={0.01}
          initialNumToRender={100}   
      />
`

Warning: Failed prop type: Invalid prop `ScrollViewComponent` of type `object` supplied to `BigList`, expected `function`.

**Comment by GollyJer** [comment]
Hi. I just installed BigList and had the same problem.
It seems everything works fine even though the error is thrown. Not sure what to do.

**Comment by marcocesarato** [comment]
Hi, this feature is related to pull request #137. I tried adding more types. Tell me if it is now fixed in the next version.

**Comment by AnisLarguet123** [comment]
the new version fixed the big, i just added this line, thank you
`    ScrollViewComponent ={ScrollView}`
