### ISSUE TITLE
scrollTo functions are not working

### ISSUE THREAD

**Issue by sabymike** [marcocesarato/react-native-big-list#17]
There seems to be an issue with the scroll methods. The `scrollToPosition` of `BigListProcessor` requires a valid value for `numColumns` otherwise the `scrollTop` value results in `NaN` and no scroll operation is performed. The `BigList` component needs to make sure it is passing the `numColumns` prop to the processor to prevent this error.

**Comment by marcocesarato** [comment]
Hi @sabymike, thanks for your pull request, it's much appreciated. Merged and released on version 1.3.13.
Thank you so much.
