### ISSUE TITLE
Layout trouble with images/videos

### ISSUE THREAD

**Issue by LouisSyfer** [marcocesarato/react-native-big-list#189]
Hi everyone, 

I just tried the package. Really impressive ! The performance is here. But... as soon as you introduce an image or a video, there's a layout problem. Maybe it should be better if the item height could be set to "auto" (for exemple). 
Or maybe I missed something. I would like to know if anybody else has the same issue and how it may be fixed...

Thanks a lot for any information

**Comment by marcocesarato** [comment]
#16
