### ISSUE TITLE
Blank items on fast scroll

### ISSUE THREAD

**Issue by rogerkerse** [marcocesarato/react-native-big-list#193]
Hi. Currently with the BigList, when scrolling fast on an actual device the items appear as blanks for some time until they get their content. I see that no re-renders are happening to the screen so it must be the internal implementation of the list.

Can something be done about it?

**Comment by rogerkerse** [comment]
Is anyone maintaining this project?

**Comment by marcocesarato** [comment]
https://marcocesarato.github.io/react-native-big-list-docs/#how-it-works

Hi, how is written on the documentation
> When list can't render your items fast enough the non-rendered components will appear as blank space.
