### ISSUE TITLE
Is there a limit?

### ISSUE THREAD

**Issue by perdomofranklin93** [marcocesarato/react-native-big-list#24]
Greetings

Thank you, for create this component. I just wanted to ask if a million items can be displayed? In this scenario it would work for Android as well as for iOS?

**Comment by marcocesarato** [comment]
Hi @perdomofranklin93, technically there is not a limit of items (only the device memory), anyway you can just try it.

**Comment by perdomofranklin93** [comment]
Hi @marcocesarato, thank you for answer, i test your component with 400,000 elements. It works pretty well, It depends on the hardware of the device, as you well mentioned. I tested with a device with 2gb of ram. 

I will leave this information here:

**Javascript**
[The longest possible array could have 232-1 = 4,294,967,295 = 4.29 billion elements.](https://stackoverflow.com/a/6155063)

**Java, kotlin, JVM**
[The theoretical limit for ArrayList capacity is Integer. MAX_VALUE, a.k.a. 2^31 - 1, a.k.a. 2,147,483,647. But you'll probably get an OutOfMemoryError long before that time because, well, you run out of memory.](https://findanyanswer.com/what-is-the-maximum-size-of-arraylist-in-java#:~:text=The%20theoretical%20limit%20for%20ArrayList,you%20run%20out%20of%20memory.)

**Swift**
[https://developer.apple.com/documentation/swift/array/1538388-capacity](https://developer.apple.com/documentation/swift/array/1538388-capacity)
