### ISSUE TITLE
bug / when list is empty, header is shown below

### ISSUE THREAD

**Issue by dougg0k** [marcocesarato/react-native-big-list#35]
Hey, there is a bug with the `renderHeader`, if the list is empty and I have set the `renderEmpty` the `renderHeader` is rendered below the `renderEmpty`, it should most likely be rendered above, since it's the header.

Edit: 
If I set `hideFooterOnEmpty` it hides the `renderHeader` which seems to be set as footer when the list is empty. There is no `renderFooter` set. 
But if I set `hideHeaderOnEmpty` and remove `hideFooterOnEmpty` it hides the `renderEmpty` component and show the header instead.

**Comment by marcocesarato** [comment]
Hi, thanks for reporting this issue, is much apreciated. This been solved on 1.3.16

**Comment by dougg0k** [comment]
Thank you for fixing it.
