### ISSUE TITLE
feature-request/num-of-columns

### ISSUE THREAD

**Issue by dougg0k** [marcocesarato/react-native-big-list#5]
Like from FlatList https://reactnative.dev/docs/flatlist#numcolumns.

I actually tried using `contentContainerStyle={{ flexDirection: "row", flexWrap: "wrap" }}` for little items, but it gave a weird behavior. Given the item header it doesnt consider row, only column.

**Comment by dougg0k** [comment]
Actually using `columnWrapperStyle={{ flexWrap: "wrap" }}` with FlatList it works, but that property is not available in BigList.

**Comment by marcocesarato** [comment]
Hi @ dougg0k, I'll be working on this feature.
I need to review the processor because it calculates the number of elements based on height, but if you have multiple columns you see the same number of elements with the current system. (So ​​if without column you see `10` elements with two columns you have to see` 20` elements but the processor only processes `10` so the other` 10` will be empty).
I need to change the item width of the list based on columns number (easy task).

**Comment by dougg0k** [comment]
Cool, thanks.

**Comment by dougg0k** [comment]
What if there was an option to wrap content in row direction, without numOfColumn, it would work automatically if you gave a prop to set the item width, it would fit based on screen and properly without need of CSS or calculation in the dev side.

**Comment by marcocesarato** [comment]
> What if there was an option to wrap content in row direction, without numOfColumn, it would work automatically if you gave a prop to set the item width, it would fit based on width available without need of style or calculation in the lib consumer side. It could be a very good addition.

The problem still with rendering processor of the recycler view so I need to review it.

**Comment by dougg0k** [comment]
I understand, if you need any help testing if you add something, let me know.

**Comment by dougg0k** [comment]
Maybe it would be as easy as having `numOfColumns` available and `const numOfColumns = Math.round(screenWidth / itemWidth)` here it worked with FlatList, no style needed.

**Comment by dougg0k** [comment]
It seems BigList already have a View as a container, maybe you could get the parent width, by setting your View container to width 100% and access the layout value and do the calculation from that, then any width from BigList parent from the lib consumer, would work, at least in theory, I didnt test this.

```
<View onLayout={(event) => {
  var {x, y, width, height} = event.nativeEvent.layout;
}} />
```

**Comment by marcocesarato** [comment]
> It seems that BigList already have a View as a container, maybe you could get the parent width, by setting your View container to width 100% and access the layout value and do the calculation from that, then any width from BigList parent from the lib consumer, would work, at least in theory, I didnt test this.
> 
> It would still need that item width prop.
> 
> ```
> <View onLayout={(event) => {
>   const {x, y, width, height} = event.nativeEvent.layout;
> }} />
> ```
> 
> You mentioned the rendering processor, I dont understand anything from it, so probably I missed something.

The processor that I mean is the following class: https://github.com/marcocesarato/react-native-big-list/blob/master/lib/BigListProcessor.js that process the height and the position of each items depending from the scroll offset of the scroll view. So even you with style it able to render items side by side with column format the processor actually don't elaborate all items.

In short actually each row is equivalent to the height of the element (like `50`) so we know that the third element will be shown at offset scrollview` 150` (index:` 3` * itemHeight: `50`) and this continue until you reach the size of the visible list. But if we have 2 elements per row it means that the third element will be in the `100` position but for the processor it is at `150`. Then, when the processor reaches the maximum size of the visible list, it stops rendering the items.

If the maximum size allows you to render `10` elements, with two columns you could render `20` but the processor currently only processes `10` and miss all position of the following elements.

Yesterday I done some tests and tried to implement it but I got some glitches that make it unusable so I need to fix them before release something.

**Comment by marcocesarato** [comment]
@dougg0k I added this feature on release `1.3.0` let me know if you find some issues and if all it's working fine.

**Comment by dougg0k** [comment]
I think the typescript type for that prop is missing and is not working properly, I set for example 5 columns but only 4 items appear and the rest of the items are not appearing below.

**Comment by dougg0k** [comment]
I think the typescript type for that prop is missing and is not working properly, I set for example 5 columns but only 4 items appear in a array of 16, while in a array of 59, only 12 appeared.

**Comment by dougg0k** [comment]
If I have a renderHeader set, is there a way to modify the width only from the list?

**Comment by marcocesarato** [comment]
> I think the typescript type for that prop is missing and is not working properly, I set for example 5 columns but only 4 items appear in a array of 16, while in a array of 59, only 12 appeared. the rest does not.

Typing, was missing, added on `1.3.1`. 

> If I have a renderHeader set, is there a way to modify the width only from the list?

Header is only width 100% at the moment. If you need to add an header with width like the others item you can prepend and item at the top of the array and render it with `renderItem`. 

Like this example:

```js

//...

const data = [{type: 'item', title: 'item 1'}, {type: 'item', title: 'item 2'}, {type: 'item', title: 'item 3'}];
data.unshift({type: 'header', title: 'My header'});

const renderItem = ({type, title}) => {
  if(type === 'header') {
    return (<MyHeader />)
  }
  return (<MyItem />);
}

//...

<BigList
  data={data}
  renderItem={renderItem}
/>
```

If by chance I misunderstood, can you give an example?

**Comment by dougg0k** [comment]
No, I meant from the `renderHeader` prop. I dont want to modify the item header. I want to modify the whole list width, because If I am using renderHeader for the whole screen, if I wrap BigList into a View with the width that I want, even the the header of the screen in renderHeader will be affected, but I only wanted the list of data itens to be smaller.

**Comment by dougg0k** [comment]
numColumns is not working as I said, only works normally without using numColumns, in a single column.

**Comment by marcocesarato** [comment]
> I think the typescript type for that prop is missing and is not working properly, I set for example 5 columns but only 4 items appear in a array of 16, while in a array of 59, only 12 appeared. the rest does not.

This now is fixed on `1.3.2`

> No, I meant from the `renderHeader` prop. I dont want to modify the item header. I want to modify the whole list `width`, because If I am using `renderHeader `for the whole screen, if I wrap `BigList` into a `View` with the `width` that I want, even the the header of the screen in `renderHeader` will be affected, but I only wanted the list of data itens to be smaller. Does that make sense?

I this cause why use `renderHeader` instead of a component above the list? 
Anyway I saw that with this feature `contentContainerStyle` is static so I can make it overwritable.

**Comment by dougg0k** [comment]
That works.

**Comment by dougg0k** [comment]
Testing here, it seems that is taking longer to load the renderHeader when scrolling back up, doesnt feel natural, stays in that white for a second.

**Comment by dougg0k** [comment]
I noticed another thing, I have a dark theme in this app, is there way to modify that white space color? Because it's always white when loading content.

**Comment by marcocesarato** [comment]
> Testing here, it seems that is taking longer to load the `renderHeader` when scrolling back up, doesnt feel natural, stays in that white for 1-2sec. Different than FlatList. It's more noticeable when I scroll fast.
> 
> Maybe the `renderHeader` shouldn't be a part of the list? But it's only there so that the BigList work without needing something like ScrollView.

Every items, like header, footer, section and items are re-rendered every time you scroll and the batch change of items change. This because improve and recycle every view unlike from flatlist that create a new view every batch and keep in cache every item. So biglist is good for a lot of items or complex layout items. So the header is re-rendered on scroll up. If you check the example that have a lot of items but basic layout it is rendered immediatly. So probably your header is very heavy to render.

> I noticed another thing, I have a dark theme in this app, is there way to modify that loading space color? Because it's always white when loading content.

The list don't set colors so probably behind your list the background is white so you have to set the background color of your root component (like on the example).


Example web app link: https://marcocesarato.github.io/react-native-big-list/

**Comment by dougg0k** [comment]
Right, I will wait for your release from `contentContainerStyle`

**Comment by marcocesarato** [comment]
Published new release and deployed new example with columns.

**Comment by dougg0k** [comment]
Thanks for all the help.

**Comment by dougg0k** [comment]
@marcocesarato I just tested, `contentContainerStyle` is also affecting `renderHeader`, same thing as just wrapping BigList in a View.
