### ISSUE TITLE
useScrollToTop  from '@react-navigation/native' error

### ISSUE THREAD

**Issue by haibert** [marcocesarato/react-native-big-list#62]
Hello Marco,

Thank you for all the hard work. 

I am trying to implement useScrollToTop with BigList and i'm getting the following error

'undefined is not an object (evaluating '_ref7.animated')

Im following the instructions from the[ react navigation docs](https://reactnavigation.org/docs/5.x/use-scroll-to-top)

Here is my code

```
import { useScrollToTop } from '@react-navigation/native'

const MyScreen = () => {

       const bigListRef = useRef()
       useScrollToTop(bigListRef)

              return (
                  <BigList
                    ref={bigListRef}
                   ....
                   />
                   )
}
```

**Comment by marxvn** [comment]
Hi @haibert 

try this
```
import { useScrollToTop } from '@react-navigation/native'

const MyScreen = () => {

const bigListRef = useRef()
useScrollToTop(React.useRef({
    scrollToTop: () => bigListRef.current?.scrollToTop({ animated = true }),
  }));

  return (
      <BigList
  ref={bigListRef}
  ....
  />
  )
}
```
I fixed this problem with PR #61 
Please upgrade to the latest version 1.4.2

**Comment by haibert** [comment]
Thank you so much! worked like a charm. didn't need to specify the animation though. This was good enough: 

```
 useScrollToTop(
        React.useRef({
            scrollToTop: () => {
                bigListRef.current.scrollToTop()
            },
        })
    )
```

**Comment by marxvn** [comment]
that's right, need to pass parameters if using version 1.4.1 or below.
