### ISSUE TITLE
Empty component cannot be full width due to its wrapped View

### ISSUE THREAD

**Issue by hoangvvo** [marcocesarato/react-native-big-list#83]
Right now, `emptyItem` is wrapped inside a <View /> so if I tried to style the Empty component as `{ width: "100%" }`, it will still not fill the width. react-native FlatList allows this to work.

![Screenshot from 2021-10-02 18-20-04](https://user-images.githubusercontent.com/40987398/135713976-6eccf08c-e5c1-4ca0-a2bb-f94076182be5.png)

https://github.com/marcocesarato/react-native-big-list/blob/master/lib/BigList.jsx#L811

I propose we either:
- remove the wrapped <View /> (preferred) 
- add { width: "100%" } to that View

**Comment by HyopeR** [comment]
This situation still continues.

**Comment by HyopeR** [comment]
This situation still continues.

**Version:**
```
"react-native-big-list": "^1.5.6",
```
